version: '3.2'

services:
  gatsby:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
  nginx:
    build:
      context: './nginx/'
    links:
      - gatsby
    ports:
      - '80:80'
      - '443:443'
